### ISSUE TITLE
loosen typing of pipe?

### ISSUE THREAD

**Issue by matthewleon** [purescript-node/purescript-node-streams#20]
currently, we have:
```purescript
foreign import pipe
  :: forall r w eff
   . Readable w eff
  -> Writable r eff
  -> Eff eff (Writable r eff)
```

I would think we'd want something more like:
```purescript
foreign import pipe
  :: forall r w eff eff' eff''
   . Union eff eff' eff''
  => Readable w eff
  -> Writable r eff'
  -> Eff eff'' (Writable r eff')
```

The readable and writable streams may have different effect rows, and by piping them together, we want the resulting effect to be a combination of the two.

**Comment by matthewleon** [comment]
(not sure if this kind of thing is possible on effect rows)

**Comment by paf31** [comment]
I think unification should just do the right thing here, no?

**Comment by matthewleon** [comment]
Yes, that's why I closed the issue. I was being dumb.
