### ISSUE TITLE
Stream write callback doesn't allow handling errors

### ISSUE THREAD

**Issue by wclr** [purescript-node/purescript-node-streams#35]
```purs
foreign import writeStringImpl
  :: forall r
   . Writable r
  -> String
  -> String
  -> Effect Unit -- callback should allow error handling
  -> Effect Boolean
```

The callback should allow error handling, for example: 
`(Nullable Error) -> Effect Unit` though the error value passed to the callback may be `undefined` or js `Error`.

**Comment by JordanMartinez** [comment]
See https://github.com/purescript/purescript/pull/4299#issuecomment-1112528546=

**Comment by JordanMartinez** [comment]
@wclr Can you provide an example that demonstrates a time where the arg will be undefined? The [docs](https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#writablewritechunk-encoding-callback) don't really clarify this, so I assumed it was always `Error` and forgot about the `null` possibility.

@thomashoneyman I think we'll need to fix this before `0.15.0` is released. Our FFI bindings cannot have wrong type signatures.

**Comment by wclr** [comment]
> Can you provide a Node.js example that demonstrates a time where the arg will be undefined?

It is undefined in v16.13.2:

```js
const fs = require("fs")
var writeStream = fs.createWriteStream("./file.txt")
writeStream.write("some", null, (err) => {
  console.log("err", err) // prints out `undefined`
  writeStream.end((endErr) => {
       console.log("endErr", endErr) // prints out `undefined`
   })
})  
```

So to use `Nullable` that means that implementation:
```js
export function write(w) {
  return chunk => done => () => w.write(chunk, null, done);
}
```

Should be changed to:
```js
export function write(w) {
  return chunk => done => () => w.write(chunk, null, (err) => done(err || null);
}
```


The same for `writeStringImpl` and `end` (this too may give the error, for example if try to end already finished stream) foreing implementations.

**Comment by JordanMartinez** [comment]
Thanks. I can confirm that. Idiomatically, it would be better if the API exposed to the end-user was `Maybe Error -> Effect Unit`.

**Comment by wclr** [comment]
> It would be better if the API exposed to the end-user was Maybe Error -> Effect Unit.

I think this is right, I just usually try to make FFI code as simple as possible.

**Comment by JordanMartinez** [comment]
My thought was that if we used `Nullable Error`, all end users would have to write something like this:
```purs
-- We want to handle both cases
\err -> do
  case toMaybe err of
    Nothing -> ...
    Just e -> ...

-- We only care if it's an actual error:
\err -> for_ (toMaybe err) \actualErr -> ...

-- We only care if it's not an error:
\err -> when (null == err) $ ...
```
Since 2/3 use `toMaybe` and the third could be written in terms of `Maybe` (e.g. `when (isNothing err) $ ...`), we could implement the FFI like this:
```purs
foreign import writeStringImpl
  :: forall r. Writable r -> String -> String -> (Nullable Error -> Effect Unit) -> Effect Boolean

writeString
  :: forall r. Writable r -> String -> String -> (Maybe Error -> Effect Unit) -> Effect Boolean
writeString w s1 s2 cb = writeStringImpl w s1 s2 (cb <<< toMaybe)
```

**Comment by JordanMartinez** [comment]
> Should be changed to
> ```
> export function write(w) {
>  return chunk => done => () => w.write(chunk, null, (err) => done(err || null));
> }
> ```

Not quite. The `err || null` part isn't needed. `toMaybe` is defined as:
```purs
toMaybe :: forall a. Nullable a -> Maybe a
toMaybe n = runFn3 nullable n Nothing Just
```
`nullable` is implemented as:
```js
export function nullable(a, r, f) {
  return a == null ? r : f(a);
}
```
and running `nullable(undefined, true, () => false)` returns `true`.

If `nullable` was implemented as `a === null` rather than `a == null`, then we'd need the `err || null` part.

**Comment by garyb** [comment]
We do tend to use `Maybe`s rather than `Nullable` in the web libraries, as it is nicer to deal with for consumers.

**Comment by JordanMartinez** [comment]
> The same for ... `end` (this too may give the error, for example if try to end already finished stream) foreign implementations.

Yeah, I can confirm this too with this example:
```js
import fs from "fs";

var file = fs.createWriteStream("./file.txt")
file.on('error', () => {});
file.write("something", () => {
  file.destroy(new Error("Muahahah!"));
  file.end((err) => {
    console.log("Example where 'err' is Error");
    console.log(err)
  });

  var file2 = fs.createWriteStream("./file2.txt")
  file2.end((err) => {
    console.log("Example where 'err' is undefined");
    console.log(err);
  });
});
```
which outputs:
```
Example where 'err' is Error
Error [ERR_STREAM_DESTROYED]: Cannot call end after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at WriteStream.Writable.end (node:internal/streams/writable:636:11)
    at file:///home/user/z.mjs:7:8
    at afterWrite (node:internal/streams/writable:497:5)
    at onwrite (node:internal/streams/writable:477:7)
    at node:internal/fs/streams:410:5
    at FSReqCallback.wrapper [as oncomplete] (node:fs:801:5) {
  code: 'ERR_STREAM_DESTROYED'
}
Example where 'err' is undefined
undefined
