### ISSUE TITLE
Stream Promises API?

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-node/purescript-node-streams#44]
Starting in Node.js v15, there is a [“Stream Promises API”](https://nodejs.org/docs/latest-v15.x/api/stream.html#stream_streams_promises_api). Do we want to support that in this package?

Would we use the `Promise` type from [__aff-promise__](https://pursuit.purescript.org/packages/purescript-aff-promise/4.0.0) or [__web-promise__](https://pursuit.purescript.org/packages/purescript-web-promise/3.0.0)?

From __web-promise__, I assume. But then we would probably want to settle this issue to make the Stream Promises API useful: https://github.com/nwolverson/purescript-aff-promise/issues/24

**Comment by MonoidMusician** [comment]
Can the functionality be made in aff without going through promises, just using the callback api this library already provides?

**Comment by jamesdbrock** [comment]
> Can the functionality be made in aff without going through promises, just using the callback api this library already provides?

Yes, I'm working on that now... https://github.com/jamesdbrock/purescript-node-streams-aff

**Comment by jamesdbrock** [comment]
Node.js seems to have three __stream__ APIs. https://nodejs.org/api/stream.html

1. The “flowing” API based on event listener callbacks
2. The “paused” API based on asynchronous completion callbacks
3. The Promise API

These three APIs were added in chronological order. When API 1 proved to not work, they added API 2, right on top of it in the same namespace. API 1 and 2 are mutually incompatible, and users are admonished to [“choose one API style.”](https://nodejs.org/api/stream.html#choose-one-api-style)

Now API 2 has proven to not work. It doesn’t work in a specific case which I need: a program which writes to *stdout* and then exits.

https://github.com/nodejs/node/issues/6456
https://github.com/nodejs/node/issues/6379
https://nodejs.org/api/process.html#a-note-on-process-io

Now there is API 3, the Promise API, which was added right on top of the other APIs in the same namespace but is incompatible with the first two APIs. 

There are hints on the internet that  API 3 might actually be able to write to *stdout* and then exit. https://github.com/sparksuite/waterfall-cli/issues/258

So I think I want a PureScript wrapper for the Streams Promises API https://nodejs.org/api/stream.html#streams-promises-api

**Comment by jamesdbrock** [comment]
I take it back, I think the Stream Promises API is also rubbish and cannot write to *stdout* and then exit.

**Comment by jamesdbrock** [comment]
I published https://pursuit.purescript.org/packages/purescript-node-streams-aff which I think solves the problem.
